MODEL:
  NAME: 'transformer'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: '/home/system7-user3/project/centroids-reid/models/jx_vit_base_p16_224-80ecf9dd.pth'
  TRANS_PRETRAIN_PATH: '/home/system7-user3/project/centroids-reid/models/jx_vit_base_p16_224-80ecf9dd.pth'
  KEEP_CAMID_CENTROIDS: True
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NO_MARGIN: True
  DEVICE_ID: ('5')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  SIE_CAMERA: True
  SIE_COE: 3.0
  JPM: True
  RE_ARRANGE: True
  DIST_TRAIN: True

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATALOADER:
  SAMPLER: 'random_identity'
  TRANS_SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 150
  EVAL_PERIOD: 40
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120
  LOG_PERIOD: 50
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

OUTPUT_DIR: '../logs/market_vit_transreid'

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 3
